name: Deploy
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      shell: bash
      env:
        GH_PWD: ${{ secrets.GH_PWD }}
        GT_PWD: ${{ secrets.GT_PWD }}
        GT_TOKEN: ${{ secrets.GT_TOKEN }}
      run: |
        git version
        pwd
        git clone --branch=source --depth=1 https://github.com/tootal/tootal.github.io
        cd tootal.github.io
        sudo apt install nodejs npm curl -y
        node --version
        npm --version
        sudo npm install hexo-cli -g
        sudo npm install
        hexo generate
        cd ./public
        git init
        git config user.name "tootal"
        git config user.email "tootal@yeah.net"
        git add .
        git commit -m "update site"
        git push --force --quiet "https://tootal:${GH_PWD}@github.com/tootal/tootal.github.io" master:master
        git push --force --quiet "https://tootal:${GT_PWD}@gitee.com/tootal/tootal" master:master
        curl -X POST --header 'Content-Type: application/json;charset=UTF-8' 'https://gitee.com/api/v5/repos/tootal/tootal/pages/builds' -d "{\"access_token\":\"${GT_TOKEN}\"}"
