name: Sync
on: page_build
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:tootal/tootal.github.io.git
          destination-repo: git@gitee.com:tootal/tootal.git
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: tootal
          gitee-password: ${{ secrets.GT_PWD }}
          gitee-repo: tootal/tootal
          branch: master